### ISSUE TITLE
{{ summary }} and {{ temperature }} never change

### ISSUE THREAD

**Issue by danielfowler** [jeremysexton/forecaster#1]
I am having a problem where my {{ summary }} is always 'Overcast' and my {{ temperature }} is always 40 degrees Fahrenheit. These are the only variables I'm using, so I imagine others aren't working either.

``` html
{{ forecaster latitude="33.5642479" longitude="-83.1784414" }}
  <div>{{ current_date format="M j l" }}</div>
  <div class="{{ icon }}">{{ summary }}</div>
  <div>{{ temperature|backspace:3 }}&deg;F</div>
  <div>{{ current_date format="g:i A" }}</div>
{{ /forecaster }}
```

I tried to reset forecaster by reinstalling, but with no success.

**Comment by jeremysexton** [comment]
Can I see your code? As far as I know, it should be working.

**Comment by danielfowler** [comment]
From forecaster.yaml:

``` yaml
api_key: c94e01b1c8d382a0c8c7ef803b372ff0
default_lat: 33.5642479
default_long: -83.1784414
default_units: auto
```

From my template:

``` html
{{ forecaster }}
  <div>{{ current_date format="M j l" }}</div>
  <div class="{{ icon }}">{{ summary }}</div>
  <div>{{ temperature|round }}&deg;F</div>
  <div>{{ current_date format="g:i A" }}</div>
{{ /forecaster }}
```

`{{ temperature }}` is now changing (it hasn't in 4 weeks until today) but it's about 15 degrees off... makes me think it's not reading the right location.

**Comment by jeremysexton** [comment]
I'll try to take a look at this as soon as I can. I'll let you know what I find.

**Comment by danielfowler** [comment]
No rush... my client hasn't noticed. :)

**Comment by danielfowler** [comment]
If I had to wager a guess... I think it's caching the weather state from the very first time it loaded, because I believe it was overcast and around 40 degrees at the time. It took me about a week to catch on that it wasn't changing (because it was overcast and cold every day).

I just plugged in the `{{ current_date }}` as the date parameter, and it appears to be accurate... fairly. It's off by 7 degrees, but that's pretty close.

``` html
{{ forecaster date="{ current_date }" }}
  <div class="forecast">
    {{ theme:partial src="ss-forecast" use_context="true" }}
    <div class="temp">{{ temperature|round }}&deg;F</div>
  </div>
{{ /forecaster }}
```

**Comment by jeremysexton** [comment]
Do you have html caching on for those pages?

**Comment by danielfowler** [comment]
Negative.

---

Daniel A Fowler
Digital Marketing Specialist & Project Manager
twitter http://www.twitter.com/danielfowler : linkedin
http://www.linkedin.com/in/danfo : google+
http://plus.google.com/113584981782119936380 : portfolio
http://www.fowlertown.com

**Comment by jeremysexton** [comment]
First of all, I'm really sorry it's taken me forever to get back to you. I do web dev sparingly and never had a chance to take a look at this until now. You figured out the issue with the date, basically. If you plug in the time, as well, it should be more accurate. I believe if you just do the date and no time, it's probably going to pull the time at midnight.

You could also check it against [Forecast](http://forecast.io) and use the "Time Machine" to get the weather at that date to see if it's working properly or not. I just used it for a site I'm currently trying to wrap up and it seems to be spot on.

If you're even still working on this site at all and run into any issues, let me know.
